const apartments = [
    {
        id: '1',
        serviceTitle: 'Washington Avenue',
        price: '$299',
        location: 'Nasirabad H/S, Chattogram',
        noOfBedRoom: '3 Bedrooms',
        noOfBathRoom: '2 Bathroom',
        thumbnail: 'https://i.ibb.co/6F5zPw9/Rectangle-394.png',
        description: '3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        rent: "$650 (negotiable)",
        serviceCharge: '8,000/= Tk per month, subject to change',
        securityDeposite: '3 month’s rent',
        flatReleasePolicy: "3 months earlier notice required",
        address: ' Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area.',
        flatSize: ' 3000 Sq Feet',
        room: '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        Floor: 'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        facilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
        additionalfacilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
    
    
    },
    {
        id: '2',
        serviceTitle: 'Family Apartment Three',
        price: '$194',
        location: 'Nasirabad H/S, Chattogram',
        noOfBedRoom: '3 Bedrooms',
        noOfBathRoom: '2 Bathroom',
        thumbnail: 'https://i.ibb.co/rx48s1H/Rectangle-396.png',
        
        description: '3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        rent: "$550 (negotiable)",
        serviceCharge: '8,000/= Tk per month, subject to change',
        securityDeposite: '3 month’s rent',
        flatReleasePolicy: "3 months earlier notice required",
        address: ' Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area.',
        flatSize: ' 3000 Sq Feet',
        room: '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        Floor: 'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        facilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
        additionalfacilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
    },
    {
        id: '3',
        serviceTitle: 'Washington Avenue',
        price: '$254',
        location: 'Nasirabad H/S, Chattogram',
        noOfBedRoom: '3 Bedrooms',
        noOfBathRoom: '2 Bathroom',
        thumbnail: 'https://i.ibb.co/rdK0gjB/Rectangle-398.png',
        description: '3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        rent: "$550 (negotiable)",
        serviceCharge: '8,000/= Tk per month, subject to change',
        securityDeposite: '3 month’s rent',
        flatReleasePolicy: "3 months earlier notice required",
        address: ' Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area.',
        flatSize: ' 3000 Sq Feet',
        room: '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        Floor: 'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        facilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
        additionalfacilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
    },
    {
        id: '4',
        serviceTitle: 'Gorgeous house',
        price: '$194',
        location: 'Nasirabad H/S, Chattogram',
        noOfBedRoom: '3 Bedrooms',
        noOfBathRoom: '2 Bathroom',
        thumbnail: 'https://i.ibb.co/gm6Pwn4/Rectangle-403.png',
        description: '3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        rent: "$550 (negotiable)",
        serviceCharge: '8,000/= Tk per month, subject to change',
        securityDeposite: '3 month’s rent',
        flatReleasePolicy: "3 months earlier notice required",
        address: ' Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area.',
        flatSize: ' 3000 Sq Feet',
        room: '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        Floor: 'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        facilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
        additionalfacilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
    },
    {
        id: '5',
        serviceTitle: 'Epic Huda Palacio',
        price: '$394',
        location: 'Nasirabad H/S, Chattogram',
        noOfBedRoom: '3 Bedrooms',
        noOfBathRoom: '2 Bathroom',
        thumbnail: 'https://i.ibb.co/jhgh6zG/Rectangle-404.png',
        description: '3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        rent: "$550 (negotiable)",
        serviceCharge: '8,000/= Tk per month, subject to change',
        securityDeposite: '3 month’s rent',
        flatReleasePolicy: "3 months earlier notice required",
        address: ' Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area.',
        flatSize: ' 3000 Sq Feet',
        room: '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        Floor: 'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        facilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
        additionalfacilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
    },
    {
        id: '6',
        serviceTitle: 'Epic Huda Palacio',
        price: '$294',
        location: 'Nasirabad H/S, Chattogram',
        noOfBedRoom: '3 Bedrooms',
        noOfBathRoom: '2 Bathroom',
        thumbnail: 'https://i.ibb.co/bmmFJZf/Rectangle-405.png',
        description: '3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.',
        rent: "$550 (negotiable)",
        serviceCharge: '8,000/= Tk per month, subject to change',
        securityDeposite: '3 month’s rent',
        flatReleasePolicy: "3 months earlier notice required",
        address: ' Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area.',
        flatSize: ' 3000 Sq Feet',
        room: '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet.',
        Floor: 'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        facilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
        additionalfacilities: '1 Modern Lift, All Modern Amenities & Semi Furnished.',
    }

];


export default apartments;